import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { NextAuthProvider } from "./api/auth/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cohen Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
